name: ExClan
main: ex.nervisking.ExClan
version: 1.0.2
authors:
  - nervisking
  - kevinazo
  - Retorns
api-version: "1.21"

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false